# fork from https://github.com/YouEclipse/waka-box-go

name: Update gist with WakaTime stats

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update-gist
    if: "!contains(github.event.head_commit.message, 'waka-box:')"
    runs-on: ubuntu-latest
    env:
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: README.md
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Update-gist
        working-directory: ./waka-box-go
        run: go run ./cmd/box/main.go 

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "waka-box: update README"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
